name: SwiftLint

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/swiftlint.yml'
      - 'SOPT-32st-Assignment/.swiftlint.yml'
      - 'SOPT-32st-Assignment/**/*.swift'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/swiftlint.yml'
      - 'SOPT-32st-Assignment/.swiftlint.yml'
      - 'SOPT-32st-Assignment/**/*.swift'

jobs:
  SwiftLint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run Swiftlint
      - run: swiftlint --config SOPT-32st-Assignment/.swiftlint.yml --strict
