name: Test
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-11
    name: Test
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          set -ex
          sudo xcode-select -s /Users/minjae/Desktop/StudyProjects/32-SOPT-TVING/SOPTving/Xcode.app

          xcodebuild test -scheme 'SOPTvingTests' \
            -destination "platform=iOS Simulator,name=iPhone 13" \
            -resultBundlePath TestResults.xcresult

      - uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: TestResults.xcresult
        if: success() || failure()
