name: Test
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-11
    name: Test
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          xcodebuild clean test -project SOPTving/SOPTving.xcodeproj -scheme SOPTvingTests -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=14.4' -resultBundlePath TestResults.xcresult
          
      - uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: TestResults.xcresult
        if: success() || failure()
