- uses: kishikawakatsumi/xcresulttool@v1
  with:
    path: TestResults.xcresult
  if: success() || failure()
  # ^ This is important because the action will be run
  # even if the test fails in the previous step.
jobs:
  test:
    runs-on: macos-11
    name: Test
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          xcodebuild -scheme MyFramework -resultBundlePath TestResults test

      - uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: TestResults.xcresult
        if: success() || failure()
        # ^ This is important because the action will be run
        # even if the test fails in the previous step.
